"""add_b2b_network_models

Revision ID: 4e78be85db86
Revises: 7ea4d9eb55fb
Create Date: 2026-06-16 21:39:10.645661
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e78be85db86'
down_revision = '7ea4d9eb55fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('b2b_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_business_id', sa.Integer(), nullable=False),
    sa.Column('buyer_business_id', sa.Integer(), nullable=False),
    sa.Column('price_tier', sa.String(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('credit_limit', sa.Float(), nullable=False),
    sa.Column('outstanding_balance', sa.Float(), nullable=False),
    sa.Column('stock_visibility', sa.String(), nullable=False),
    sa.Column('catalog_category', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_business_id'], ['users.id'], name=op.f('fk_b2b_connections_buyer_business_id_users')),
    sa.ForeignKeyConstraint(['seller_business_id'], ['users.id'], name=op.f('fk_b2b_connections_seller_business_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_b2b_connections')),
    sa.UniqueConstraint('seller_business_id', 'buyer_business_id', name='uq_b2b_connections_seller_buyer')
    )
    with op.batch_alter_table('b2b_connections', schema=None) as batch_op:
        batch_op.create_index('ix_b2b_connections_buyer', ['buyer_business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_b2b_connections_id'), ['id'], unique=False)
        batch_op.create_index('ix_b2b_connections_seller', ['seller_business_id'], unique=False)

    op.create_table('b2b_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_business_id', sa.Integer(), nullable=False),
    sa.Column('seller_business_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(), nullable=False),
    sa.Column('order_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('cgst_total', sa.Float(), nullable=False),
    sa.Column('sgst_total', sa.Float(), nullable=False),
    sa.Column('igst_total', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_business_id'], ['users.id'], name=op.f('fk_b2b_orders_buyer_business_id_users')),
    sa.ForeignKeyConstraint(['seller_business_id'], ['users.id'], name=op.f('fk_b2b_orders_seller_business_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_b2b_orders'))
    )
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.create_index('ix_b2b_orders_buyer', ['buyer_business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_b2b_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_b2b_orders_order_number'), ['order_number'], unique=True)
        batch_op.create_index('ix_b2b_orders_seller', ['seller_business_id'], unique=False)

    op.create_table('connection_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_business_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_business_id'], ['users.id'], name=op.f('fk_connection_codes_seller_business_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_codes'))
    )
    with op.batch_alter_table('connection_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connection_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_connection_codes_id'), ['id'], unique=False)
        batch_op.create_index('ix_connection_codes_seller_code', ['seller_business_id', 'code'], unique=False)

    op.create_table('shared_ledgers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_business_id', sa.Integer(), nullable=False),
    sa.Column('buyer_business_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_snapshot', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_business_id'], ['users.id'], name=op.f('fk_shared_ledgers_buyer_business_id_users')),
    sa.ForeignKeyConstraint(['seller_business_id'], ['users.id'], name=op.f('fk_shared_ledgers_seller_business_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shared_ledgers'))
    )
    with op.batch_alter_table('shared_ledgers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shared_ledgers_id'), ['id'], unique=False)
        batch_op.create_index('ix_shared_ledgers_seller_buyer', ['seller_business_id', 'buyer_business_id'], unique=False)

    op.create_table('b2b_order_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('hsn_sac', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('cgst_rate', sa.Float(), nullable=False),
    sa.Column('sgst_rate', sa.Float(), nullable=False),
    sa.Column('igst_rate', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['b2b_orders.id'], name=op.f('fk_b2b_order_line_items_order_id_b2b_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_b2b_order_line_items_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_b2b_order_line_items'))
    )
    with op.batch_alter_table('b2b_order_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_b2b_order_line_items_id'), ['id'], unique=False)
        batch_op.create_index('ix_b2b_order_line_items_order', ['order_id'], unique=False)

    op.create_table('invoice_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('payment_mode', sa.String(), nullable=True),
    sa.Column('payment_date', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_invoice_payments_customer_id_customers')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_payments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_payments')),
    sa.UniqueConstraint('business_id', 'idempotency_key', name='uq_invoice_payments_biz_idem')
    )
    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_payments_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_invoice_payments_customer', ['business_id', 'customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_payments_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index('ix_invoice_payments_invoice', ['business_id', 'invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_payments_invoice_id'), ['invoice_id'], unique=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('unit',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Nos'"))
        batch_op.alter_column('hsn_sac',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('barcode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('batch_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('mrp',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('cost_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('selling_price',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('category',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        if op.get_context().dialect.name == 'sqlite':
            batch_op.create_index(batch_op.f('ix_inventory_barcode'), ['barcode'], unique=False)
            batch_op.create_index('ix_inventory_business_stock', ['business_id', 'stock'], unique=False)
            batch_op.create_index(batch_op.f('ix_inventory_product_id'), ['product_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_inventory_product_name'), ['product_name'], unique=False)
            batch_op.create_index(batch_op.f('ix_inventory_vendor_id'), ['vendor_id'], unique=False)
        if op.get_context().dialect.name == 'sqlite':
            batch_op.create_foreign_key(batch_op.f('fk_inventory_vendor_id_vendors'), 'vendors', ['vendor_id'], ['id'])
            batch_op.create_foreign_key(batch_op.f('fk_inventory_product_id_products'), 'products', ['product_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.alter_column('paid_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('payment_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('payment_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('gstin_buyer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('place_of_supply',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('invoice_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('cgst_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('sgst_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('igst_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('cess_total',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('irn',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('ack_no',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('ack_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        if op.get_context().dialect.name == 'sqlite':
            batch_op.create_index('ix_invoice_business_date', ['business_id', 'invoice_date'], unique=False)
            batch_op.create_index('ix_invoice_business_status', ['business_id', 'status'], unique=False)
            batch_op.create_index(batch_op.f('ix_invoices_customer'), ['customer'], unique=False)
            batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_invoices_invoice_id'), ['invoice_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        if op.get_context().dialect.name == 'sqlite':
            batch_op.create_foreign_key(batch_op.f('fk_invoices_customer_id_customers'), 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_mode',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        if op.get_context().dialect.name == 'sqlite':
            batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        if op.get_context().dialect.name == 'sqlite':
            batch_op.create_foreign_key(batch_op.f('fk_payments_invoice_id_invoices'), 'invoices', ['invoice_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(), nullable=True))
        batch_op.alter_column('gstin',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('state_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('pan',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    # Backfill unique Crockford Base32 BizIDs for existing users
    import random
    chars = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
    bind = op.get_bind()
    existing_users = bind.execute(sa.text("SELECT id FROM users")).fetchall()
    used_ids = set()
    for row in existing_users:
        user_id = row[0]
        while True:
            public_id = "BA-" + "".join(random.choice(chars) for _ in range(6))
            if public_id not in used_ids:
                used_ids.add(public_id)
                break
        bind.execute(
            sa.text("UPDATE users SET public_id = :public_id WHERE id = :id"),
            {"public_id": public_id, "id": user_id}
        )

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_public_id'))
        batch_op.alter_column('pan',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('state_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('gstin',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('public_id')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        if op.get_context().dialect.name == 'sqlite':
            batch_op.drop_constraint(batch_op.f('fk_payments_invoice_id_invoices'), type_='foreignkey')
            batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.alter_column('payment_mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        if op.get_context().dialect.name == 'sqlite':
            batch_op.drop_constraint(batch_op.f('fk_invoices_customer_id_customers'), type_='foreignkey')
        if op.get_context().dialect.name == 'sqlite':
            batch_op.drop_index(batch_op.f('ix_invoices_status'))
            batch_op.drop_index(batch_op.f('ix_invoices_invoice_id'))
            batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))
            batch_op.drop_index(batch_op.f('ix_invoices_customer'))
            batch_op.drop_index('ix_invoice_business_status')
            batch_op.drop_index('ix_invoice_business_date')
        batch_op.alter_column('ack_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ack_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('irn',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('cess_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('igst_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('sgst_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('cgst_total',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('subtotal',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('invoice_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('place_of_supply',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('gstin_buyer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('payment_mode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('paid_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        if op.get_context().dialect.name == 'sqlite':
            batch_op.drop_constraint(batch_op.f('fk_inventory_product_id_products'), type_='foreignkey')
            batch_op.drop_constraint(batch_op.f('fk_inventory_vendor_id_vendors'), type_='foreignkey')
        if op.get_context().dialect.name == 'sqlite':
            batch_op.drop_index(batch_op.f('ix_inventory_vendor_id'))
            batch_op.drop_index(batch_op.f('ix_inventory_product_name'))
            batch_op.drop_index(batch_op.f('ix_inventory_product_id'))
            batch_op.drop_index('ix_inventory_business_stock')
            batch_op.drop_index(batch_op.f('ix_inventory_barcode'))
        batch_op.alter_column('category',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('selling_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('cost_price',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('mrp',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('batch_no',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('barcode',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('hsn_sac',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Nos'"))

    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_payments_invoice_id'))
        batch_op.drop_index('ix_invoice_payments_invoice')
        batch_op.drop_index(batch_op.f('ix_invoice_payments_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_invoice_payments_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_payments_customer_id'))
        batch_op.drop_index('ix_invoice_payments_customer')
        batch_op.drop_index(batch_op.f('ix_invoice_payments_business_id'))

    op.drop_table('invoice_payments')
    with op.batch_alter_table('b2b_order_line_items', schema=None) as batch_op:
        batch_op.drop_index('ix_b2b_order_line_items_order')
        batch_op.drop_index(batch_op.f('ix_b2b_order_line_items_id'))

    op.drop_table('b2b_order_line_items')
    with op.batch_alter_table('shared_ledgers', schema=None) as batch_op:
        batch_op.drop_index('ix_shared_ledgers_seller_buyer')
        batch_op.drop_index(batch_op.f('ix_shared_ledgers_id'))

    op.drop_table('shared_ledgers')
    with op.batch_alter_table('connection_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_connection_codes_seller_code')
        batch_op.drop_index(batch_op.f('ix_connection_codes_id'))
        batch_op.drop_index(batch_op.f('ix_connection_codes_code'))

    op.drop_table('connection_codes')
    with op.batch_alter_table('b2b_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_b2b_orders_seller')
        batch_op.drop_index(batch_op.f('ix_b2b_orders_order_number'))
        batch_op.drop_index(batch_op.f('ix_b2b_orders_id'))
        batch_op.drop_index('ix_b2b_orders_buyer')

    op.drop_table('b2b_orders')
    with op.batch_alter_table('b2b_connections', schema=None) as batch_op:
        batch_op.drop_index('ix_b2b_connections_seller')
        batch_op.drop_index(batch_op.f('ix_b2b_connections_id'))
        batch_op.drop_index('ix_b2b_connections_buyer')

    op.drop_table('b2b_connections')
    # ### end Alembic commands ###
