"""baseline schema

Revision ID: c0017902b685
Revises: 
Create Date: 2026-06-10 22:51:32.919574
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0017902b685'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_log'))
    )
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_log_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_log_id'), ['id'], unique=False)

    op.create_table('alert_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('whatsapp_number', sa.String(), nullable=True),
    sa.Column('alert_overdue', sa.Boolean(), nullable=True),
    sa.Column('alert_low_stock', sa.Boolean(), nullable=True),
    sa.Column('alert_expiry', sa.Boolean(), nullable=True),
    sa.Column('alert_daily_summary', sa.Boolean(), nullable=True),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('expiry_days_threshold', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_configs'))
    )
    with op.batch_alter_table('alert_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_configs_business_id'), ['business_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_alert_configs_id'), ['id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('session_title', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('model_tier', sa.String(), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_session_id'), ['session_id'], unique=False)

    op.create_table('customers',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_gstin'), ['gstin'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=False)

    op.create_table('document_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.String(), nullable=True),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.String(), nullable=True),
    sa.Column('embedding_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_embeddings'))
    )
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_embeddings_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_embeddings_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_embeddings_id'), ['id'], unique=False)

    op.create_table('products',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_sac', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('is_service', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_hsn_sac'), ['hsn_sac'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('rate_limit_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('requests_per_minute', sa.Integer(), nullable=True),
    sa.Column('requests_per_day', sa.Integer(), nullable=True),
    sa.Column('max_tokens_per_day', sa.Integer(), nullable=True),
    sa.Column('complex_per_day', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rate_limit_configs'))
    )
    with op.batch_alter_table('rate_limit_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rate_limit_configs_business_id'), ['business_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_rate_limit_configs_id'), ['id'], unique=False)

    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('model_tier', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('cached_tokens', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_token_usage'))
    )
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_usage_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_id'), ['id'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('rows_count', sa.Integer(), nullable=True),
    sa.Column('upload_time', sa.String(), nullable=True),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_files'))
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_file_hash'), ['file_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('business_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('vendors',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('state_code', sa.String(), nullable=True),
    sa.Column('pan', sa.String(), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('last_gstr1_filed', sa.String(), nullable=True),
    sa.Column('filing_reliability', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendors_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_gstin'), ['gstin'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendors_name'), ['name'], unique=False)

    op.create_table('inventory',
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('supplier', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('hsn_sac', sa.String(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('batch_no', sa.String(), nullable=True),
    sa.Column('mrp', sa.Float(), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_product_id_products')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_inventory_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory'))
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_business_id'), ['business_id'], unique=False)
        batch_op.create_index('ix_inventory_business_stock', ['business_id', 'stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_product_name'), ['product_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_inventory_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('invoices',
    sa.Column('invoice_id', sa.String(), nullable=True),
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('product', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('invoice_date', sa.String(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('paid_amount', sa.Float(), nullable=True),
    sa.Column('payment_date', sa.String(), nullable=True),
    sa.Column('payment_mode', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('gstin_buyer', sa.String(), nullable=True),
    sa.Column('place_of_supply', sa.String(), nullable=True),
    sa.Column('invoice_type', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('cgst_total', sa.Float(), nullable=True),
    sa.Column('sgst_total', sa.Float(), nullable=True),
    sa.Column('igst_total', sa.Float(), nullable=True),
    sa.Column('cess_total', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('irn', sa.String(), nullable=True),
    sa.Column('ack_no', sa.String(), nullable=True),
    sa.Column('ack_date', sa.String(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_invoices_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices'))
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_business_date', ['business_id', 'invoice_date'], unique=False)
        batch_op.create_index('ix_invoice_business_status', ['business_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_customer'), ['customer'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('vendor_name', sa.String(), nullable=True),
    sa.Column('po_date', sa.String(), nullable=True),
    sa.Column('expected_date', sa.String(), nullable=True),
    sa.Column('received_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('gstin_buyer', sa.String(), nullable=True),
    sa.Column('place_of_supply', sa.String(), nullable=True),
    sa.Column('invoice_type', sa.String(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('cgst_total', sa.Float(), nullable=True),
    sa.Column('sgst_total', sa.Float(), nullable=True),
    sa.Column('igst_total', sa.Float(), nullable=True),
    sa.Column('cess_total', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('irn', sa.String(), nullable=True),
    sa.Column('ack_no', sa.String(), nullable=True),
    sa.Column('ack_date', sa.String(), nullable=True),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_purchase_orders_vendor_id_vendors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_orders'))
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_number'), ['po_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_vendor_id'), ['vendor_id'], unique=False)

    op.create_table('invoice_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('hsn_sac', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('discount_pct', sa.Float(), nullable=True),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('cess_rate', sa.Float(), nullable=True),
    sa.Column('taxable_value', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('cess_amount', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_line_items_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_invoice_line_items_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_line_items'))
    )
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_line_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_line_items_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_line_items_product_id'), ['product_id'], unique=False)

    op.create_table('payments',
    sa.Column('customer', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('due_date', sa.String(), nullable=True),
    sa.Column('paid', sa.String(), nullable=True),
    sa.Column('file_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_mode', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('purchase_order_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('hsn_sac', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('cgst_rate', sa.Float(), nullable=True),
    sa.Column('sgst_rate', sa.Float(), nullable=True),
    sa.Column('igst_rate', sa.Float(), nullable=True),
    sa.Column('taxable_value', sa.Float(), nullable=True),
    sa.Column('cgst_amount', sa.Float(), nullable=True),
    sa.Column('sgst_amount', sa.Float(), nullable=True),
    sa.Column('igst_amount', sa.Float(), nullable=True),
    sa.Column('line_total', sa.Float(), nullable=True),
    sa.Column('received_qty', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_order_line_items_product_id_products')),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], name=op.f('fk_purchase_order_line_items_purchase_order_id_purchase_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_order_line_items'))
    )
    with op.batch_alter_table('purchase_order_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_line_items_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_line_items_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_line_items_purchase_order_id'), ['purchase_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_items_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_line_items_id'))

    op.drop_table('purchase_order_line_items')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))
        batch_op.drop_index(batch_op.f('ix_payments_file_id'))
        batch_op.drop_index(batch_op.f('ix_payments_business_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_product_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_line_items_id'))

    op.drop_table('invoice_line_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_business_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index(batch_op.f('ix_invoices_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_file_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_customer'))
        batch_op.drop_index(batch_op.f('ix_invoices_business_id'))
        batch_op.drop_index('ix_invoice_business_status')
        batch_op.drop_index('ix_invoice_business_date')

    op.drop_table('invoices')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_vendor_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_product_name'))
        batch_op.drop_index(batch_op.f('ix_inventory_product_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_file_id'))
        batch_op.drop_index('ix_inventory_business_stock')
        batch_op.drop_index(batch_op.f('ix_inventory_business_id'))
        batch_op.drop_index(batch_op.f('ix_inventory_barcode'))

    op.drop_table('inventory')
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendors_name'))
        batch_op.drop_index(batch_op.f('ix_vendors_id'))
        batch_op.drop_index(batch_op.f('ix_vendors_gstin'))
        batch_op.drop_index(batch_op.f('ix_vendors_business_id'))

    op.drop_table('vendors')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_file_hash'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_business_id'))

    op.drop_table('uploaded_files')
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_usage_id'))
        batch_op.drop_index(batch_op.f('ix_token_usage_business_id'))

    op.drop_table('token_usage')
    with op.batch_alter_table('rate_limit_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rate_limit_configs_id'))
        batch_op.drop_index(batch_op.f('ix_rate_limit_configs_business_id'))

    op.drop_table('rate_limit_configs')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_hsn_sac'))
        batch_op.drop_index(batch_op.f('ix_products_business_id'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))

    op.drop_table('products')
    with op.batch_alter_table('document_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_embeddings_id'))
        batch_op.drop_index(batch_op.f('ix_document_embeddings_file_id'))
        batch_op.drop_index(batch_op.f('ix_document_embeddings_business_id'))

    op.drop_table('document_embeddings')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_name'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_gstin'))
        batch_op.drop_index(batch_op.f('ix_customers_business_id'))

    op.drop_table('customers')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_session_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_id'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_business_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('alert_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_configs_id'))
        batch_op.drop_index(batch_op.f('ix_alert_configs_business_id'))

    op.drop_table('alert_configs')
    with op.batch_alter_table('action_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_log_id'))
        batch_op.drop_index(batch_op.f('ix_action_log_business_id'))

    op.drop_table('action_log')
    # ### end Alembic commands ###
