"""Add Phase 3 and Phase 4 schema updates

Revision ID: f78e8836b7b1
Revises: b4e7a2d8f1c3
Create Date: 2026-07-03 18:03:52.366511
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f78e8836b7b1'
down_revision = 'b4e7a2d8f1c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_log_business_id'))
        batch_op.drop_index(batch_op.f('ix_action_log_id'))
        batch_op.create_index(batch_op.f('ix_action_logs_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_logs_id'), ['id'], unique=False)

    with op.batch_alter_table('ai_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_business_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_id'))
        batch_op.create_index(batch_op.f('ix_ai_feedback_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_feedback_id'), ['id'], unique=False)

    with op.batch_alter_table('ai_query_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_override_business_id'))
        batch_op.drop_index(batch_op.f('ix_query_override_id'))
        batch_op.drop_index(batch_op.f('ix_query_override_query_norm'))
        batch_op.drop_constraint(batch_op.f('uq_query_override_biz_query'), type_='unique')
        batch_op.create_index(batch_op.f('ix_ai_query_overrides_business_id'), ['business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_query_overrides_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_query_overrides_query_norm'), ['query_norm'], unique=False)
        batch_op.create_unique_constraint('uq_ai_query_overrides_biz_query', ['business_id', 'query_norm'])

    with op.batch_alter_table('alert_configs', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_alert_configs_business_uid'))

    with op.batch_alter_table('b2b_invite_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connection_codes_code'))
        batch_op.drop_index(batch_op.f('ix_connection_codes_id'))
        batch_op.drop_index(batch_op.f('ix_connection_codes_seller_code'))
        batch_op.create_index(batch_op.f('ix_b2b_invite_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_b2b_invite_codes_id'), ['id'], unique=False)
        batch_op.create_index('ix_b2b_invite_codes_seller_code', ['seller_business_id', 'code'], unique=False)

    with op.batch_alter_table('b2b_ledgers', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_shared_ledgers_id'))
        batch_op.drop_index(batch_op.f('ix_shared_ledgers_seller_buyer'))
        batch_op.drop_index(batch_op.f('uq_shared_ledgers_uid'))
        batch_op.create_index(batch_op.f('ix_b2b_ledgers_id'), ['id'], unique=False)
        batch_op.create_index('ix_b2b_ledgers_seller_buyer', ['seller_business_id', 'buyer_business_id'], unique=False)

    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_business_settings_business_uid'))

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_customers_business_uid'))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_expenses_business_uid'))

    with op.batch_alter_table('godowns', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_godowns_business'))
        batch_op.drop_index(batch_op.f('uq_godowns_business_uid'))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_inventory_business_uid'))

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.alter_column('mrp',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('uq_invoice_line_items_uid'))

    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_invoice_payments_business_uid'))
        batch_op.create_index(batch_op.f('ix_invoice_payments_shift_id'), ['shift_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_invoice_payments_shift_id_register_shifts'), 'register_shifts', ['shift_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('print_template', sa.String(), nullable=True))
        batch_op.alter_column('invoice_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_invoices_business_uid'))
        batch_op.create_index(batch_op.f('ix_invoices_shift_id'), ['shift_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_uid_token'), ['uid_token'], unique=True)
        batch_op.create_foreign_key(batch_op.f('fk_invoices_shift_id_register_shifts'), 'register_shifts', ['shift_id'], ['id'])

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_journal_entries_business_uid'))

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_payments_business_uid'))
        batch_op.create_index(batch_op.f('ix_payments_shift_id'), ['shift_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_payments_shift_id_register_shifts'), 'register_shifts', ['shift_id'], ['id'])

    with op.batch_alter_table('period_locks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_period_locks_business_uid'))

    with op.batch_alter_table('product_barcodes', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_product_barcodes_business_uid'))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_products_business_uid'))

    with op.batch_alter_table('purchase_invoice_line_items', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_purchase_invoice_line_items_uid'))

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_purchase_invoices_business_uid'))

    with op.batch_alter_table('purchase_order_line_items', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_purchase_order_line_items_uid'))

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_purchase_orders_business_uid'))

    with op.batch_alter_table('rate_limit_configs', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_rate_limit_configs_business_uid'))

    with op.batch_alter_table('register_shifts', schema=None) as batch_op:
        batch_op.alter_column('opening_expected',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('closing_float',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_stock_ledger_business_uid'))

    with op.batch_alter_table('stock_transfer_line_items', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.TEXT(),
               type_=sa.String(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_stock_transfer_line_items_uid'))

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_stock_transfers_business'))
        batch_op.drop_index(batch_op.f('uq_stock_transfers_business_uid'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('counter_prefix',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('staff_login_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('uq_vendors_business_uid'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_vendors_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('staff_login_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('counter_prefix',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('stock_transfers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_stock_transfers_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.create_index(batch_op.f('ix_stock_transfers_business'), ['business_id'], unique=False)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('stock_transfer_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_stock_transfer_line_items_uid'), ['uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('stock_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_stock_ledger_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('register_shifts', schema=None) as batch_op:
        batch_op.alter_column('closing_float',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('opening_expected',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('rate_limit_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_rate_limit_configs_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_purchase_orders_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('purchase_order_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_purchase_order_line_items_uid'), ['uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('purchase_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_purchase_invoices_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('purchase_invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_purchase_invoice_line_items_uid'), ['uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_products_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('product_barcodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_product_barcodes_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('period_locks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_period_locks_business_uid'), ['business_id', 'uid'], unique=1)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payments_shift_id_register_shifts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payments_shift_id'))
        batch_op.create_index(batch_op.f('uq_payments_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_journal_entries_business_uid'), ['business_id', 'uid'], unique=1)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invoices_shift_id_register_shifts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoices_uid_token'))
        batch_op.drop_index(batch_op.f('ix_invoices_shift_id'))
        batch_op.create_index(batch_op.f('uq_invoices_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('invoice_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('print_template')
        batch_op.drop_column('uid_token')

    with op.batch_alter_table('invoice_payments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_invoice_payments_shift_id_register_shifts'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_invoice_payments_shift_id'))
        batch_op.create_index(batch_op.f('uq_invoice_payments_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('invoice_line_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_invoice_line_items_uid'), ['uid'], unique=1)
        batch_op.alter_column('expiry_date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('mrp',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_inventory_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('godowns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_godowns_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.create_index(batch_op.f('ix_godowns_business'), ['business_id'], unique=False)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_expenses_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_customers_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('business_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_business_settings_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('b2b_ledgers', schema=None) as batch_op:
        batch_op.drop_index('ix_b2b_ledgers_seller_buyer')
        batch_op.drop_index(batch_op.f('ix_b2b_ledgers_id'))
        batch_op.create_index(batch_op.f('uq_shared_ledgers_uid'), ['uid'], unique=1)
        batch_op.create_index(batch_op.f('ix_shared_ledgers_seller_buyer'), ['seller_business_id', 'buyer_business_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_shared_ledgers_id'), ['id'], unique=False)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('b2b_invite_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_b2b_invite_codes_seller_code')
        batch_op.drop_index(batch_op.f('ix_b2b_invite_codes_id'))
        batch_op.drop_index(batch_op.f('ix_b2b_invite_codes_code'))
        batch_op.create_index(batch_op.f('ix_connection_codes_seller_code'), ['seller_business_id', 'code'], unique=False)
        batch_op.create_index(batch_op.f('ix_connection_codes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_connection_codes_code'), ['code'], unique=1)

    with op.batch_alter_table('alert_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_alert_configs_business_uid'), ['business_id', 'uid'], unique=1)
        batch_op.alter_column('uid',
               existing_type=sa.String(length=36),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('ai_query_overrides', schema=None) as batch_op:
        batch_op.drop_constraint('uq_ai_query_overrides_biz_query', type_='unique')
        batch_op.drop_index(batch_op.f('ix_ai_query_overrides_query_norm'))
        batch_op.drop_index(batch_op.f('ix_ai_query_overrides_id'))
        batch_op.drop_index(batch_op.f('ix_ai_query_overrides_business_id'))
        batch_op.create_unique_constraint(batch_op.f('uq_query_override_biz_query'), ['business_id', 'query_norm'])
        batch_op.create_index(batch_op.f('ix_query_override_query_norm'), ['query_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_override_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_override_business_id'), ['business_id'], unique=False)

    with op.batch_alter_table('ai_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_feedback_id'))
        batch_op.drop_index(batch_op.f('ix_ai_feedback_business_id'))
        batch_op.create_index(batch_op.f('ix_feedback_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_business_id'), ['business_id'], unique=False)

    with op.batch_alter_table('action_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_logs_id'))
        batch_op.drop_index(batch_op.f('ix_action_logs_business_id'))
        batch_op.create_index(batch_op.f('ix_action_log_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_action_log_business_id'), ['business_id'], unique=False)

    # ### end Alembic commands ###
